#define VIE_MAX_BAT 50
#define NIVEAU_MAX_BAT 10


#define NIVEAU_MAX_TROUPE 20

#define FACTO_RESSOURCES 5
#define FACTO_VIE_BAT 2
#define FACTO_BAT_GUERRE 20

#define FACTO_VIE_SOLDAT 60
#define FACTO_ATTAQUE_TROUPE_SOLD 20

#define FACTO_VIE_MAGICIEN 30
#define FACTO_ATTAQUE_TROUPE_MAG 25

#define FACTO_SOIN_TROUPE 10